/*

	This file is part of GALE (Generic Adaptation Language and Engine).

    GALE is free software: you can redistribute it and/or modify it under the 
    terms of the GNU Lesser General Public License as published by the Free 
    Software Foundation, either version 3 of the License, or (at your option) 
    any later version.

    GALE is distributed in the hope that it will be useful, but WITHOUT ANY 
    WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS 
    FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for 
    more details.

    You should have received a copy of the GNU Lesser General Public License
    along with GALE. If not, see <http://www.gnu.org/licenses/>.
    
 */
/**
 * EventGEBListenerService.java
 * Last modified: $Date$
 * In revision:   $Revision$
 * Modified by:   $Author$
 *
 * Copyright (c) 2008-2011 Eindhoven University of Technology.
 * All Rights Reserved.
 *
 * This software is proprietary information of the Eindhoven University
 * of Technology. It may be used according to the GNU LGPL license.
 */
package org.netbeans.j2ee.wsdl.geb.eventgeblistener;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.7-b01- Generated
 * source version: 2.1
 * 
 */
@WebServiceClient(name = "eventGEBListenerService", targetNamespace = "http://j2ee.netbeans.org/wsdl/GEB/eventGEBListener", wsdlLocation = "http://localhost:18080/geb/eventGEBListenerService?wsdl")
public class EventGEBListenerService extends Service {

	private final static URL EVENTGEBLISTENERSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(org.netbeans.j2ee.wsdl.geb.eventgeblistener.EventGEBListenerService.class
					.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = org.netbeans.j2ee.wsdl.geb.eventgeblistener.EventGEBListenerService.class
					.getResource(".");
			url = new URL(baseUrl,
					"http://localhost:18080/geb/eventGEBListenerService?wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:18080/geb/eventGEBListenerService?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		EVENTGEBLISTENERSERVICE_WSDL_LOCATION = url;
	}

	public EventGEBListenerService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public EventGEBListenerService() {
		super(EVENTGEBLISTENERSERVICE_WSDL_LOCATION, new QName(
				"http://j2ee.netbeans.org/wsdl/GEB/eventGEBListener",
				"eventGEBListenerService"));
	}

	/**
	 * 
	 * @return returns EventGEBListenerPortType
	 */
	@WebEndpoint(name = "eventGEBListenerPort")
	public EventGEBListenerPortType getEventGEBListenerPort() {
		return super.getPort(new QName(
				"http://j2ee.netbeans.org/wsdl/GEB/eventGEBListener",
				"eventGEBListenerPort"), EventGEBListenerPortType.class);
	}

	/**
	 * 
	 * @param features
	 *            A list of {@link javax.xml.ws.WebServiceFeature} to configure
	 *            on the proxy. Supported features not in the
	 *            <code>features</code> parameter will have their default
	 *            values.
	 * @return returns EventGEBListenerPortType
	 */
	@WebEndpoint(name = "eventGEBListenerPort")
	public EventGEBListenerPortType getEventGEBListenerPort(
			WebServiceFeature... features) {
		return super.getPort(new QName(
				"http://j2ee.netbeans.org/wsdl/GEB/eventGEBListener",
				"eventGEBListenerPort"), EventGEBListenerPortType.class,
				features);
	}

}
